
set search_path = scanner_registry;

INSERT into site (site_name, description) VALUES
('ISI', 'USC Information Sciences Institute'),
('ALTAMED', 'Altamed Medical Group'),
('RAND', 'RAND Corporation'),
('UCSD', 'University of California, San Diego');
 
INSERT INTO node (site_id, node_name, host_url, host_port, base_path, description, is_master) VALUES
(1, 'Test Master', 'https://scanner.misd.isi.edu', 9998, '/scanner/query/', 'ISI Test Network Master Node', true),
(2, 'Test Worker', 'https://scanner-node1.misd.isi.edu', 8888, '/scanner/dataset/','ISI Test Network Worker Node (ALTAMED SIM)', false),
(3, 'Test Worker', 'https://scanner-node2.misd.isi.edu', 8888, '/scanner/dataset/', 'ISI Test Network Worker Node (RAND SIM)', false),
(4, 'Test Worker', 'https://scanner-node3.misd.isi.edu', 8888, '/scanner/dataset/', 'ISI Test Network Worker Node (UCSD SIM)', false);

INSERT INTO scanner_user (user_name, email, HSPC_documents, Phone, Reports_To, Active, First_Name, Middle_Initial, Last_Name, PubMed_Author_ID, is_superuser) VALUES
('scanner', 'dmeeker@rand.org, laura@isi.edu, mdarcy@isi.edu, serban@isi.edu', null, null, 0, true, 'SCANNER', NULL, 'Network Administrator', NULL, true),
('dmeeker', 'dmeeker@rand.org', null, '2139262658', 0, true, 'Daniella', 'EP', 'Meeker', NULL, false),
('laura', 'laura@isi.edu', null, null, 0, true, 'Laura', NULL, 'Pearlman', NULL, false),
('mdarcy', 'mdarcy@isi.edu', null, null, 0, true, 'Mike', NULL, 'D''Arcy', NULL, false),
('serban', 'serban@isi.edu', null, null, 0, true, 'Serban', NULL, 'Voinea', NULL, false);

INSERT INTO study (study_name, description, IRB_ID, Protocol, Study_Owner, Start_Date, End_Date, Clinical_Trials_ID, Analysis_Plan, study_status_type_id) VALUES
('SCANNER', 'SCANNER Network', '', 'Administrative study used to manage global SCANNER Network configuration', 1, null, null, null, null,1),
('MTM', 'Medication Therapy Management', '', 'Analyze MTM data on multiple sites with both OCEANS and GLORE', 2, '2013-08-15', '2013-08-15', null, 'Very Important Analysis on Multiple Sites',1),
('BEARI', 'Behavioral Economics for Acute Respitory Infections', '', 'Analyze BEARI data on multiple ISI VMs with both OCEANS and GLORE', 2, '2013-08-15', '2013-08-15', null, 'Determine if performance is contingent on principal diagnosis',1);

INSERT INTO standard_role(standard_role_name, description, create_by_default, add_to_study_policy_by_default, add_to_user_role_by_default) VALUES
('Principal Investigator','Manages study roles and defines study policies',true,true,true),
('Site PI','Manages access to local site resources by defining site policies',true,false,false),
('Investigator', 'Can execute analysis programs based on predefined study and site policies',true,false,true);

INSERT INTO study_role (study_id,role_within_study) VALUES
(1,'ISI Site Administrator'),
(1,'ALTAMED Site Administrator'),
(1,'RAND Site Administrator'),
(1,'UCSD Site Administrator'),
(2,'Principal Investigator'),
(2,'Site PI'),
(2,'Investigator'),
(3,'Principal Investigator'),
(3,'Site PI'),
(3,'Investigator');

INSERT INTO user_role(user_id, role_id) VALUES
(2, 3),
(2, 5),
(2, 7),
(2, 8),
(3, 4),
(3, 7),
(3, 10),
(4, 1),
(4, 2),
(4, 7),
(5, 7);

INSERT INTO study_management_policy(study_id, role_id) VALUES
(2,5),
(3,8);

INSERT INTO study_requested_site(study_id, site_id) VALUES
(2,1),
(2,2),
(2,3),
(2,4),
(3,1),
(3,3);

INSERT INTO site_policy(site_id, role_id) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(1,6),
(3,9);

INSERT INTO tool_library (library_name, version, description) VALUES
('OCEANS', '1', 'Executes Meta-Regression Across Multiple Sites'),
('GLORE', '1', 'Executes Virtually Pooled Analysis Across Multiple Sites'),
('PTR', '1', 'Executes Prep to Research Analysis Across Multiple Sites');

INSERT INTO analysis_tool (tool_name, tool_path, Tool_Parent_Library_ID, Tool_Description, Input_Format_Specifications, Output_Format_Specifications, Information_Email) VALUES
('Logistic Regression', '/oceans/lr', 1, 'Meta-regression with logit', '', '', 'michael.matheny@vanderbilt.edu'),
('Logistic Regression', '/glore/lr', 2, 'Virtually pooled logistic regression ', '', '', 'x1jiang@ucsd.edu'),
('Prep to Research', '/ptr', 3, 'Aggregate patient counts based on OMOP concept matching ', '', '', 'dmeeker@rand.org');

INSERT INTO data_set_definition (data_set_name, description, Data_Processing_XML, Data_Processing_Program, Author_UID, Originating_Study_ID, Data_Set_Confidentiality_Level) VALUES
('MTM-1', 'MTM Sample Dataset 1', null, null, 2, 2, 100),
('BEARI-1', 'BEARI Sample Dataset 1', null, null, 3, 3, 100),
('PTR', 'Prep to Research Dataset', null, null, 2, 1, 100);

INSERT INTO data_set_instance ( Data_Set_Definition_ID, data_set_instance_name, description, node_id, data_source) VALUES
(1, 'MTM ALTAMED', 'MTM Simulation data generated by Altamed', 2, 'MTM_SIMULATED_ALTAMED.csv'),
(1, 'MTM RAND', 'MTM Simulation data generated by RAND', 3, 'MTM_SIMULATED_RAND.csv'),
(1, 'MTM UCSD', 'MTM Simulation data generated by UCSD', 4, 'MTM_SIMULATED_UCSD.csv'),
(3, 'PTR ALTAMED', 'PTR Simulation data generated by Altamed', 2, 'PTR_SIMULATED_ALTAMED.csv'),
(3, 'PTR RAND', 'PTR Simulation data generated by RAND', 3, 'PTR_SIMULATED_RAND.csv'),
(3, 'PTR UCSD', 'PTR Simulation data generated by UCSD', 4, 'PTR_SIMULATED_UCSD.csv');

INSERT INTO study_policy_statement (study_id, data_set_definition_id, policy_originator, attestation, role_id, analysis_tool_id, access_mode, policy_status_id) VALUES
(2, 1, 2, ' DataSetDefinition 1 will be analyzed with with GLORE Logistic Regression in a mode without approval before transfer of aggregate/patient-level data by role Principal Investigator.  ', 5, 2, 0, 0),
(2, 1, 2, ' DataSetDefinition 1 will be analyzed with with GLORE Logistic Regression in a mode without approval before transfer of aggregate/patient-level data by role Investigator.  ', 7, 2, 0, 0),
(2, 1, 2, ' DataSetDefinition 1 will be analyzed with with OCEANS Logistic Regression in a mode with approval before transfer of aggregate/patient-level data by role Principal Investigator.  ', 5, 1, 1, 0),
(2, 1, 2, ' DataSetDefinition 1 will be analyzed with with OCEANS Logistic Regression in a mode with approval before transfer of aggregate/patient-level data by role Investigator.  ', 7, 1, 1, 0),
(2, 1, 2, ' DataSetDefinition 1 will be analyzed with with OCEANS Logistic Regression in a mode without approval before transfer of aggregate/patient-level data by role Principal Investigator.  ', 5, 1, 0, 0),
(2, 1, 2, ' DataSetDefinition 1 will be analyzed with with OCEANS Logistic Regression in a mode without approval before transfer of aggregate/patient-level data by role Investigator.  ', 7, 1, 0, 0),
(3, 2, 2, ' DataSetDefinition 2 will be analyzed with with GLORE Logistic Regression in a mode without approval before transfer of aggregate/patient-level data by role Principal Investigator.  ', 8, 2, 0, 0),
(3, 2, 2, ' DataSetDefinition 2 will be analyzed with with GLORE Logistic Regression in a mode without approval before transfer of aggregate/patient-level data by role Investigator.  ', 10, 2, 0, 0);

INSERT INTO analysis_policy_statement (data_set_instance_id, role_id, analysis_tool_id, access_mode_id, policy_status_id, parent_study_policy_statement_id) VALUES
(1,7,1,1,0,4),
(2,7,1,0,0,6),
(3,7,1,0,0,6),
(1,7,2,0,0,2),
(2,7,2,0,0,2),
(3,7,2,0,0,2);

INSERT INTO data_set_variable_metadata (data_set_definition, variable_name, variable_description, variable_type, variable_options) VALUES
(1, 'group', 'group', 'binary', NULL),
(1, 'male', 'male', 'binary', NULL),
(1, 'eth', 'ethnicity', 'binary', NULL),
(1, 'age', 'age', 'integer', NULL),
(1, 'smoke', 'smoking history', 'binary', NULL),
(1, 'categorical_insurance', 'insurance status ', 'binary', NULL),
(1, 'a1c baseline', 'HbA1c at baseline', 'continuous', NULL),
(1, 'sybp baseline', 'Systolic BP at baseline', 'continuous', NULL),
(1, 'dibp baseline', 'Diastolic BP at baseline', 'continuous', NULL),
(1, 'ldl baseline', 'LDL at basleine', 'continuous', NULL),
(1, 'totchol baseline', 'Total cholesterol baseline measurement', 'continuous', NULL),
(1, 'trig baseline', 'Triglycerides baseline measurement', 'continuous', NULL),
(1, 'hdl baseline', 'HDL baseline measurement', 'continuous', NULL),
(1, 'bmi baseline', 'BMI baseline', 'continuous', NULL),
(1, 'days between index date and final measure date', 'days between index date and final measure date', 'integer', NULL),
(1, 'number of visits', 'number of visits', 'integer', NULL),
(1, 'a1c final', 'a1c final', 'continuous', NULL),
(1, 'bmi final', 'bmi final', 'continuous', NULL),
(1, 'sybp final', 'sybp final', 'continuous', NULL),
(1, 'dibp final', 'dibp final', 'continuous', NULL),
(1, 'ldl final', 'ldl final', 'continuous', NULL),
(1, 'totchol final', 'totchol final', 'continuous', NULL),
(1, 'trig final', 'trig final', 'continuous', NULL),
(1, 'hdl final', 'hdl final', 'continuous', NULL),
(1, 'outcome_a1c_final_lt_9', '1 if final A1C is less than 9', 'binary', NULL);
